### ISSUE TITLE
Where's version 2.19?

### ISSUE THREAD

**Issue by miszmaniac** [dart-lang/homebrew-dart#135]
Hi,

I noticed link is missing for version 2.19. 
Currently stable channel points to 3.0.0 which is not stable version for flutter.
Am I missing something or is this an issue?

**Comment by orestesgaolin** [comment]
I found that there's [`dart-sdk`](https://formulae.brew.sh/formula/dart-sdk) formula that lets us install 2.19

**Comment by mayorbyrne** [comment]
Things got messy when I tried using dart-sdk. It'd be nice if the official dart brew would update for 2.19!

**Comment by miszmaniac** [comment]
I know - had the same issue.

**Comment by Chippy-A** [comment]
me too.

**Comment by whesse** [comment]
I don't know what you mean when you say the stable channel points to 3.0.0.  When I run brew upgrade dart, it upgrades to 2.19.4.

It will upgrade to a 3.0.0 version if you use the --HEAD option, but otherwise, it should be 2.19.4
The dart.rb formula file might be misleading, because it shows the HEAD version at the top of the file, but the default stable version is below that section.

The command
brew install dart
installs 2.19.4, and the command
brew install --HEAD dart
installs 3.0.0-322.0.dev.
Both of these print the message "run brew unlink dart" when you try and install the other one. Unlinking works, and lets you install the other one.

brew install dart-beta installs the current beta version.

**Comment by aaronfranke** [comment]
The problem I am having is that Homebrew claims it's installing 2.19.6, but it actually installs 3.0.0-edge.

```
% brew reinstall dart-sdk             
==> Fetching dart-sdk
==> Downloading https://ghcr.io/v2/homebrew/core/dart-sdk/manifests/2.19.6
Already downloaded: /Users/aaronfranke/Library/Caches/Homebrew/downloads/159b2f92defa059d2b7f7e4ab1d297c929c6f910386a832db1917120dbd07486--dart-sdk-2.19.6.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/dart-sdk/blobs/sha256:18ac957619fe81347ae7a84c9580fcf96d04683bd6f0281e2cdbd98269b33084
Already downloaded: /Users/aaronfranke/Library/Caches/Homebrew/downloads/4dc0ebfa8ca2e694aa587d749d7dbe0fbdb404460ff4d7137fa5f26300b564e4--dart-sdk--2.19.6.arm64_ventura.bottle.tar.gz
==> Reinstalling dart-sdk 
==> Pouring dart-sdk--2.19.6.arm64_ventura.bottle.tar.gz
Warning: This keg was marked linked already, continuing anyway
🍺  /opt/homebrew/Cellar/dart-sdk/2.19.6: 997 files, 509.4MB
==> Running `brew cleanup dart-sdk`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

aaronfranke@Aaron-Franke-MBP-2065 glTF-Validator % which dart
/opt/homebrew/Cellar/dart-sdk/2.19.6/libexec/bin//dart

aaronfranke@Aaron-Franke-MBP-2065 glTF-Validator % dart --version         
Dart SDK version: 3.0.0-edge.042c3f6c76ab82ead5d61192ef0ed075aa0b394f (be) (Wed Mar 29 19:58:33 2023 +0000) on "macos_arm64"
```

I would expect that if the folder is called `2.19.6` and it downloads a file called `dart-sdk-2.19.6.bottle_manifest.json` then it should be downloading version `2.19.6` not `3.0.0-edge`.
