### ISSUE TITLE
How to remove dart --HEAD? 

### ISSUE THREAD

**Issue by andesappal** [dart-lang/homebrew-dart#80]
Hi @athomas, I have an issue where
```
s-MBP:~ johnappleseed$ brew info dart
dart-lang/dart/dart: stable 2.8.4, HEAD
The Dart SDK
https://dart.dev
Conflicts with:
  dart-beta (because dart-beta ships the same binaries)
/usr/local/Cellar/dart/2.8.4 (502 files, 486MB) *
  Built from source on 2020-06-30 at 14:13:49
From: https://github.com/dart-lang/homebrew-dart/blob/master/dart.rb
==> Options
--HEAD
	Install HEAD version
==> Caveats
Please note the path to the Dart SDK:
  /usr/local/opt/dart/libexec
s-MBP:~ johnappleseed$ 
``` 
How do I only use the stable release 2.8.4? Thanks.

**Comment by athomas** [comment]
brew is just telling you that it also has a HEAD version available and that won't go a way unless we remove that option. But unless you use `--HEAD` when invoking brew you're on stable.

If you want to be certain, try `dart --version`. If that gives you 2.8.4 then you're on stable, otherwise you'd get `2.9.0-x.0.dev` (`x` changes every couple days).

If you try `brew info node` you'll get a similar output.
